// <auto-generated />
using System;
using APIPix.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIPix.Data.Migrations
{
    [DbContext(typeof(MyContext))]
    [Migration("20240217220537_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("APIPix.Domain.Entities.ChavePix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoChavePix")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Chaves");
                });

            modelBuilder.Entity("APIPix.Domain.Entities.DestinoPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChaveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChaveId");

                    b.ToTable("DestinosPagamentos");
                });

            modelBuilder.Entity("APIPix.Domain.Entities.OrigemPagamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChaveId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChaveId");

                    b.ToTable("OrigensPagamentos");
                });

            modelBuilder.Entity("APIPix.Domain.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DestinoPagamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Horario")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrigemPagamentoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestinoPagamentoId");

                    b.HasIndex("OrigemPagamentoId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("APIPix.Domain.Entities.DestinoPagamento", b =>
                {
                    b.HasOne("APIPix.Domain.Entities.ChavePix", "Chave")
                        .WithMany()
                        .HasForeignKey("ChaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chave");
                });

            modelBuilder.Entity("APIPix.Domain.Entities.OrigemPagamento", b =>
                {
                    b.HasOne("APIPix.Domain.Entities.ChavePix", "Chave")
                        .WithMany()
                        .HasForeignKey("ChaveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chave");
                });

            modelBuilder.Entity("APIPix.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("APIPix.Domain.Entities.DestinoPagamento", "DestinoPagamento")
                        .WithMany("Transacoes")
                        .HasForeignKey("DestinoPagamentoId");

                    b.HasOne("APIPix.Domain.Entities.OrigemPagamento", "OrigemPagamento")
                        .WithMany("Transacoes")
                        .HasForeignKey("OrigemPagamentoId");

                    b.Navigation("DestinoPagamento");

                    b.Navigation("OrigemPagamento");
                });

            modelBuilder.Entity("APIPix.Domain.Entities.DestinoPagamento", b =>
                {
                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("APIPix.Domain.Entities.OrigemPagamento", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
